apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i79i5dbvr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i79i5dbvr-go 
  name: i79i5dbvr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i79i5dbvr-go 
